In [1]:
import numpy as np
import pandas as pd
import mnist
import keras

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

Using TensorFlow backend.

In [2]:
df_train = pd.read_csv('./fashionmnist/fashion-mnist_train.csv')
df_test = pd.read_csv('./fashionmnist/fashion-mnist_test.csv')

In [3]:
df_train.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df_label_train = df_train['label']
df_label_test = df_test['label']

In [5]:
df_label_train.unique()

array([2, 9, 6, 0, 3, 4, 5, 8, 7, 1])

In [6]:
df_img_train = df_train.drop('label', axis=1)
df_img_test = df_test.drop('label', axis=1)

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 359.3 MB

In [8]:
df_img_train = (df_img_train/255) * 2 - 1
df_img_test = (df_img_test/255) * 2 - 1

In [9]:
df_img_train.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.0,-1.0,-1.000000,-1.0,-1.0,...,-1.000000,-1.0,-1.0,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0
1,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.0,-1.0,-1.000000,-1.0,-1.0,...,-1.000000,-1.0,-1.0,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0
2,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.0,-1.0,-0.960784,-1.0,-1.0,...,-1.000000,-1.0,-1.0,-0.764706,-0.662745,-1.000000,-1.0,-1.0,-1.0,-1.0
3,-1.0,-1.0,-1.0,-0.992157,-0.984314,-1.0,-1.0,-1.000000,-1.0,-1.0,...,-0.976471,-1.0,-1.0,-1.000000,-1.000000,-0.992157,-1.0,-1.0,-1.0,-1.0
4,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.0,-1.0,-1.000000,-1.0,-1.0,...,-1.000000,-1.0,-1.0,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0

In [10]:
df_img_train.describe()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,...,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000
mean,-0.999993,-0.999952,-0.999723,-0.999201,-0.998055,-0.996773,-0.993680,-0.982759,-0.955435,-0.886363,...,-0.728428,-0.817250,-0.869896,-0.859848,-0.821060,-0.859518,-0.933172,-0.978405,-0.993290,-0.999449
std,0.000743,0.002126,0.009587,0.019238,0.033780,0.045774,0.064433,0.110536,0.186819,0.300663,...,0.451335,0.383172,0.329252,0.344832,0.406514,0.354113,0.232273,0.136452,0.073388,0.016673
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
50%,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
75%,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-0.545098,-0.929412,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
max,-0.874510,-0.717647,0.772549,0.286275,0.780392,0.803922,0.756863,1.000000,0.992157,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.333333

In [11]:
print(df_img_train.shape)
print(df_img_test.shape)

(60000, 784)
(10000, 784)

In [23]:
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

In [24]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

In [25]:
model.fit(
  df_img_train,
  to_categorical(df_label_train),
  epochs=10,
  batch_size=32,
)

Epoch 1/10
60000/60000 [==============================] - 3s 42us/step - loss: 0.4974 - accuracy: 0.8190
Epoch 2/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.3815 - accuracy: 0.8586
Epoch 3/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.3507 - accuracy: 0.8708
Epoch 4/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.3265 - accuracy: 0.8795
Epoch 5/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.3097 - accuracy: 0.8850
Epoch 6/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.2965 - accuracy: 0.8896
Epoch 7/10
60000/60000 [==============================] - 2s 41us/step - loss: 0.2833 - accuracy: 0.8951
Epoch 8/10
60000/60000 [==============================] - 3s 42us/step - loss: 0.2715 - accuracy: 0.8990
Epoch 9/10
60000/60000 [==============================] - 2s 42us/step - loss: 0.2612 - accuracy: 0.9028
Epoch 10/10
60000/60000 [==============================] - 3s 42us/step - loss: 0.2563 - accuracy: 0.9049

In [26]:
model.evaluate(
  df_img_test,
  to_categorical(df_label_test)
)

10000/10000 [==============================] - 0s 17us/step

[0.3083886031746864, 0.8924000263214111]

In [16]:
model.save_weights('model.h10')

In [17]:
predictions = model.predict(df_img_test)

In [28]:
df_label_test.shape

(10000,)

In [30]:
predictions

array([[8.9748555e-01, 6.4910601e-08, 4.3693747e-02, ..., 3.6893275e-12,
        7.8502708e-05, 1.1805326e-08],
       [5.9107488e-13, 1.0000000e+00, 1.8192597e-17, ..., 7.0835281e-21,
        3.1293185e-16, 5.6776385e-20],
       [1.7464260e-02, 4.1556082e-04, 8.6131465e-01, ..., 1.8583478e-07,
        1.7160565e-03, 4.2394922e-07],
       ...,
       [1.6839804e-11, 4.2412135e-18, 3.8226210e-12, ..., 4.3632429e-14,
        1.0000000e+00, 2.0132058e-18],
       [3.2265132e-04, 2.5588392e-07, 6.0256390e-04, ..., 2.9351494e-08,
        9.9008852e-01, 6.3854224e-09],
       [2.2430331e-05, 9.9925524e-01, 5.4601616e-05, ..., 2.2959052e-09,
        6.7028968e-06, 3.9179056e-08]], dtype=float32)